<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/preloader.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/bootstrap.min.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/slick.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/meanmenu.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/owl.carousel.min.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/animate.min.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/backToTop.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/jquery.fancybox.min.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/fontAwesome5Pro.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/elegantFont.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/default.css" />
<link rel="stylesheet" href="{{ asset('assets/frontend') }}/css/style.css" />
